version: '3.7'

services:
  database:
    image: postgres
    container_name: InventoryDB
    restart: always
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=inventory
    volumes:
      - pgdata:/data/postgres
    networks:
      - inventory
volumes:
  pgdata:
    driver: local
networks:
  inventory:
