version: "3.7"

services:
  database:
    image: postgres
    container_name: melanzane
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=melanzaneDB
    volumes:
      - pgdata:/data/postgres
volumes:
  pgdata:
    driver: local