version: "3.7"

services:
  db:
    image: postgres
    container_name: MelanzaneDB
    restart: always
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=melanzane
    volumes:
      - pgdata:/data/postgres
    networks:
      - melanzane
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: MelanzaneApp
    ports:
      - 3000:3000
    volumes:
      - .:/app
    links:
      - db
    depends_on:
      - db
    networks:
      - melanzane
volumes:
  pgdata:
    driver: local
networks:
  melanzane:
    external: true